name       : graph-tool
version    : 2.26
release    : 2
source     :
    - https://downloads.skewed.de/graph-tool/graph-tool-2.26.tar.bz2 : df6273dc5ef327a0eaf1ef1c46751fce4c0b7573880944e544287b85a068f770
license    : GPL-3.0-or-later
component  : programming.python
summary    : Efficient python module for analysis of graphs
description: |
    Graph-tool is an efficient python module for manipulation and statistical analysis of graphs
builddeps  :
    - pkgconfig(cairomm-1.0)
    - pkgconfig(expat)
    - pkgconfig(libsparsehash)
    - pkgconfig(py3cairo)
    - pkgconfig(python3)
    - CGAL-devel
    - libboost-devel
    - matplotlib
    - scipy
rundeps    :
    - matplotlib
    - python3-cairo
    - scipy
setup      : |
    %configure PYTHON=python3
build      : |
    # build with -j1 to limit memory usage (this is a memory monster)
    %make -j1
install    : |
    %make_install
