name       : graph-tool
version    : '2.43'
release    : 12
source     :
    - https://downloads.skewed.de/graph-tool/graph-tool-2.43.tar.zst : 70fdf0402ac7b0f234b0cfa89d95ee047ab4a9133892d78d1041c6e58b276534
license    : GPL-3.0-or-later
component  : programming.python
summary    : Efficient python module for analysis of graphs
description: |
    Graph-tool is an efficient python module for manipulation and statistical analysis of graphs
builddeps  :
    - pkgconfig(cairomm-1.0)
    - pkgconfig(expat)
    - pkgconfig(libsparsehash)
    - pkgconfig(py3cairo)
    - pkgconfig(python3)
    - CGAL-devel
    - libboost-devel
    - matplotlib
    - scipy
rundeps    :
    - matplotlib
    - python3-cairo
    - scipy
# If clang set to yes, the submodules give an error when imported
#clang      : yes
environment: |
    # workaround for bug in boost 1.72
    export CPPFLAGS="$CPPFLAGS -DHAVE_BOOST_COROUTINE"
setup      : |
    %configure PREFIX=/usr PYTHON=python3
build      : |
    # Maximum observed single compile job size is around 8 GiB Resident with sizes in the range 1.5-5 GiB the most common.
    # Likely due to poor job parallelism in make, the build will fan out to $CPUs -> 4-6 CPUs -> 1-2 CPUs.
    # For systems with 16 GiB RAM, make -j2 is almost suitable.
    # For systems with 32 GiB RAM, make -j7 is probably the maximum.
    # For systems with 48 GiB RAM, make -j12 is the top.
    # For systems with 64 GiB RAM, make -j16 is probably the maximum. (Should be used for the Buildserver)
    # Swap partitions/files must be used while building.
    %make
install    : |
    %make_install
